### ISSUE TITLE
TypeError: confusion_matrix() takes 2 positional arguments but 3 were given

### ISSUE THREAD

**Issue by 1806610292** [tsunghan-wu/RandLA-Net-pytorch#22]
when I run python train_SemanticKITTI.py ,
an error happen:
100%|███████████████████████████████████████| 4541/4541 [04:12<00:00, 17.99it/s]
100%|█████████████████████████████████████████| 909/909 [18:11<00:00,  1.20s/it]
  0%|                                                   | 0/136 [00:08<?, ?it/s]
Traceback (most recent call last):
  File "train_SemanticKITTI.py", line 197, in <module>
    main()
  File "train_SemanticKITTI.py", line 193, in main
    trainer.train()
  File "train_SemanticKITTI.py", line 138, in train
    mean_iou = self.validate()
  File "train_SemanticKITTI.py", line 167, in validate
    iou_calc.add_data(end_points)
  File "/home/tukrin/ZYD_3D/RandLA-Net-pytorch-main/utils/metric.py", line 29, in add_data
    conf_matrix = confusion_matrix(labels_valid, pred_valid, np.arange(0, self.cfg.num_classes, 1))
TypeError: confusion_matrix() takes 2 positional arguments but 3 were given

I don"t know how to solve this problem,can you help me? thanks!!!

**Comment by huixiancheng** [comment]
It's caused by the version of sklearn.
See [this](https://stackoverflow.com/questions/70346971/confusion-matrix-takes-2-positional-arguments-but-3-were-given.) to slove. 
~~~
conf_matrix = confusion_matrix(labels_valid, pred_valid, labels=np.arange(0, self.cfg.num_classes, 1))
~~~

**Comment by 1806610292** [comment]
@huixiancheng thanks,has solved!

**Comment by Marine98k** [comment]
> It's caused by the version of sklearn. See [this](https://stackoverflow.com/questions/70346971/confusion-matrix-takes-2-positional-arguments-but-3-were-given.) to slove.
> 
> ```
> conf_matrix = confusion_matrix(labels_valid, pred_valid, labels=np.arange(0, self.cfg.num_classes, 1))
> ```
as  your advice i change the code like this 
        from sklearn.metrics import confusion_matrix
        conf_matrix = confusion_matrix(labels_valid, pred_valid, lables=np.arange(0, self.cfg.num_classes, 1))
but another problem accured 
       TypeError: confusion_matrix() got an unexpected keyword argument 'lables'
do you know how to slove it ,looking for your advice.
